In [ ]:
# load the model from disk
import pickle
line_1_OCA = pickle.load(open('line_1_OCA_ver3.sav', 'rb'))
line_2_OCA = pickle.load(open('line_2_OCA_ver3.sav', 'rb'))
line_2_SA = pickle.load(open('line_2_SA_ver3.sav', 'rb'))
line_1_SA = pickle.load(open('line_1_SA_ver3.sav', 'rb'))
line_1_SA_per = pickle.load(open('line_1_SA_per3.sav', 'rb'))
line_2_SA_per = pickle.load(open('line_2_SA_per3.sav', 'rb'))


[08:21:09] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[08:21:09] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[08:21:09] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[08:21:09] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
[08:21:09] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


In [ ]:
import numpy as np


In [ ]:
#Line_1_OCA
a, b, c, d, e, f, g =float(input('Цветность, град. ')), float(input('Мутность, мг/л ')), float(input('PH ')), float(input('Железо общее, мг/л ')), float(input('Щелочность, мг-экв./л ')), float(input('Аммоний, мг/л ')), float(input('Известь, мг/л '))

inp = np.array([[a, b, c, d, e, f, g]])
model = line_1_OCA
model.predict(inp) #output



Цветность, град. 65
Мутность, мг/л 10.3
PH 7
Железо общее, мг/л 2.8
Щелочность, мг-экв./л 0.75
Аммоний, мг/л 0.14
Известь, мг/л 0


array([9.589848], dtype=float32)

In [ ]:
#Line_1_SA
a, b, c, d, e, f, g, h = float(input('Цветность, град. ')), float(input('Мутность, мг/л ')), float(input('Марганец, мг/л. ')), float(input('Железо общее, мг/л. ')), float(input('Щелочность, мг-экв./л. ')),  float(input('Аммоний, мг/л. ')), float(input('Известь, мг/л. '))
inp = np.array([[a, b, c, d, e, f, g]])
model = line_1_SA
model.predict(inp)  #output Сульфат алюминия, мг/л 
model_per = line_1_SA_per
model_per.predict(inp) #output Перманганат калия, мг/л
 

Цветность, град. 64
Мутность, мг/л 8.5
PH 7.3
Марганец, мг/л. 0
Железо общее, мг/л. 2.6
Щелочность, мг-экв./л. 0.7
Аммоний, мг/л. 0
Известь, мг/л. 10


array([0.00503647], dtype=float32)

In [ ]:
Q = float(input('Фактическая производительность станции, тыс. куб.м/сут.'))
coag = model.predict(inp)[0]
flok = g
coag_price = 12690 #Цена сульфата алюминия руб/тонн без НДС
flok_price = 10791.6 #Цена извести руб/тонн без НДС

day_coast = (coag* Q *(100/16.1) * coag_price/1000 + flok * (100/67) * flok_price/1000) * Q /1000

print('Cтоимость комбинации сульфат алюминия + известь', day_coast, 'тыс. руб без НДС/сут.')



In [ ]:
model.predict(inp)

array([13.13642], dtype=float32)

In [ ]:
#Line_2_SA
a, b, c, d, e, f, g = float(input('Цветность, град. ')), float(input('Мутность, мг/л ')), float(input('Марганец, мг/л. ')), float(input('Железо общее, мг/л. ')), float(input('Щелочность, мг-экв./л. ')),  float(input('Аммоний, мг/л. ')), float(input('Известь, мг/л. '))
inp = np.array([[a, b, c, d, e, f, g]])
model = line_2_SA
model.predict(inp) #output Сульфат алюминия, мг/л
model_per = line_2_SA_per
model_per.predict(inp) #output Перманганат калия, мг/л

Цветность, град. 56
Мутность, мг/л 7.9
PH 7.3
Марганец, мг/л. 0
Железо общее, мг/л. 2.7
Щелочность, мг-экв./л. 0.7
Аммоний, мг/л. 0
Известь, мг/л. 11


array([-0.01815343], dtype=float32)

In [ ]:
model.predict(inp)

array([0.])

In [ ]:
Q = float(input('Фактическая производительность станции, тыс. куб.м/сут.'))
coag = model.predict(inp)[0]
flok = g
coag_price = 12690 #Цена сульфата алюминия руб/тонн без НДС
flok_price = 10791.6 #Цена извести руб/тонн без НДС

day_coast = (coag* Q *(100/16.1) * coag_price/1000 + flok * (100/67) * flok_price/1000) * Q /1000

print('Cтоимость комбинации сульфат алюминия + известь', day_coast, 'тыс. руб без НДС/сут.')


In [ ]:
#Line_2_OCA
a, b, c, d, e, f, g =float(input('Цветность, град. ')), float(input('Мутность, мг/л ')), float(input('PH ')), float(input('Железо общее, мг/л ')), float(input('Щелочность, мг-экв./л ')), float(input('Аммоний, мг/л ')), float(input('Известь, мг/л '))

inp = np.array([[a, b, c, d, e, f, g]])
model = line_2_OCA
model.predict(inp) #output


Цветность, град. 64
Мутность, мг/л 10.9
PH 7
Железо общее, мг/л 2.9
Щелочность, мг-экв./л 0.6
Аммоний, мг/л 0.21
Известь, мг/л 0


array([13.747452], dtype=float32)